name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Configuração do Java
      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      # Build e teste do backend
      - name: Build e Teste Backend
        working-directory: ./core
        run: |
          chmod +x mvnw
          ./mvnw clean verify
      
      # Configuração do Node
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'
      
      - name: Install Dependencies
        working-directory: ./front
        run: |
          npm ci
          npm run build:ci

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy Backend para Render
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_BACK }}"
          
      - name: Deploy Frontend para Render
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_FRONT }}"